const RESET_STORE = 'COMMON/RESET_STORE';
const OPEN_LEFT_SIDEBAR = 'COMMON/OPEN_LEFT_SIDEBAR';
const OPEN_RIGHT_SIDEBAR = 'COMMON/OPEN_RIGHT_SIDEBAR';
const CLOSE_LEFT_SIDEBAR = 'COMMON/CLOSE_LEFT_SIDEBAR';
const CLOSE_RIGHT_SIDEBAR = 'COMMON/CLOSE_RIGHT_SIDEBAR';
const TOGGLE_LEFT_SIDEBAR = 'COMMON/TOGGLE_RIGHT_SIDEBAR';
const TOGGLE_RIGHT_SIDEBAR = 'COMMON/TOGGLE_RIGHT_SIDEBAR';

export {
  RESET_STORE,
  OPEN_LEFT_SIDEBAR,
  OPEN_RIGHT_SIDEBAR,
  CLOSE_LEFT_SIDEBAR,
  CLOSE_RIGHT_SIDEBAR,
  TOGGLE_LEFT_SIDEBAR,
  TOGGLE_RIGHT_SIDEBAR
};

export default {
  RESET_STORE,
  OPEN_LEFT_SIDEBAR,
  OPEN_RIGHT_SIDEBAR,
  CLOSE_LEFT_SIDEBAR,
  CLOSE_RIGHT_SIDEBAR,
  TOGGLE_LEFT_SIDEBAR,
  TOGGLE_RIGHT_SIDEBAR
};
