const RESET_STORE = 'COMMON/RESET_STORE';
const OPEN_DRAWER = 'COMMON/OPEN_DRAWER';
const CLOSE_DRAWER = 'COMMON/CLOSE_DRAWER';
const TOGGLE_DRAWER = 'COMMON/TOGGLE_DRAWER';

export {
  RESET_STORE,
  OPEN_DRAWER,
  CLOSE_DRAWER,
  TOGGLE_DRAWER
};

export default {
  RESET_STORE,
  OPEN_DRAWER,
  CLOSE_DRAWER,
  TOGGLE_DRAWER
};
